site_name: 'first-ml-model'
site_description: 'Main documentation for the first-ml-model'
repo_url: https://github.com/divakaivan/first-ml-model
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'